ipeline {
    agent any

    tools {
        gradle 'Gradle'
    }

    environment {
        DOCKER_IMAGE = 'ad'
        DOCKER_TAG = 'v1.1'
        DOCKER_REGISTRY = 'docker.io'
        DOCKER_REPO = 'manikiran0096/ad-service'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build ad') {
            steps {
                dir('src/ad') {   
                    sh './gradlew clean build'  
                }
            }
        }

        stage('Test ad') {
            steps {
                dir('src/ad') {
                    sh './gradlew test'  
                }
            }
        }

        stage('Check Docker Path') {
            steps {
                script {
                    sh 'echo "Docker Path: $(which docker)"'
                    sh "docker --version"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:$DOCKER_TAG /var/lib/jenkins/workspace/ad_micro_services/src/ad"
                }
            }
        }

        stage('Push to Registry') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: "https://$DOCKER_REGISTRY"]) {
                    sh "docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_REPO:$DOCKER_TAG"
                    sh "docker push $DOCKER_REPO:$DOCKER_TAG"
                }
            }
        }
    }
}
