pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "cartservice"
        DOCKER_TAG = "v1"
        REGISTRY = "manikiran0096/cartservice" // Replace with actual registry if needed
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/rockey096/ultimate-devops-project-demo.git' // Replace with actual repo URL
            }
        }

        stage('Restore Dependencies') {
            steps {
                sh 'dotnet restore src/cart.csproj'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build src/cart/src/cart.csproj --configuration Release --no-restore'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'dotnet test src/cart/tests/cart.tests.csproj --configuration Release --no-restore'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG /src/cart/"
            }
        }

    //     stage('Push Docker Image') {
    //         steps {
    //             withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
    //                 sh "docker push $REGISTRY/$DOCKER_IMAGE:$DOCKER_TAG"
    //             }
    //         }
    //     }

    //     stage('Deploy') {
    //         steps {
    //             echo 'Deploying the Cart Service...'
    //             // Add deployment script (Kubernetes, Docker Compose, etc.)
    //         }
    //     }
    // }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
    }
}
}
