pipeline {
    agent any

    tools {
        maven 'Maven'  // Should match the name in Global Tool Configuration
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('ad') {
            steps {
                dir('src/ad') {   // Navigate to the specific microservice directory
                    sh 'mvn clean install'  // Change this based on your build tool
                }
            }
        }

        stage('Test ad') {
            steps {
                dir('src/ad') {
                    sh 'mvn test'  // Run tests for the microservice
                }
            }
        }

        stage('Package ad') {
            steps {
                dir('src/ad') {
                    sh 'docker build -t my-service-1:latest .'  // Build Docker image
                }
            }
        }

        stage('Push to Docker Registry') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub', url: '']) {
                    dir('src/ad') {
                        sh 'docker tag my-service-1:latest my-dockerhub-user/my-service-1:latest'
                        sh 'docker push my-dockerhub-user/my-service-1:latest'
                    }
                }
            }
        }
    }
}
