pipeline {
    agent any

    tools {
        gradle 'Gradle'  // Ensure Gradle is configured in Global Tool Configuration
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build ad') {
            steps {
                dir('src/ad') {   // Navigate to the specific microservice directory
                    sh './gradlew clean build'  // Using Gradle wrapper for build
                }
            }
        }

        stage('Test ad') {
            steps {
                dir('src/ad') {
                    sh './gradlew test'  // Run tests using Gradle
                }
            }
        }

        // stage('Package ad') {
        //     steps {
        //         dir('src/ad') {
        //             sh 'docker build -t my-service-1:latest .'  // Build Docker image
        //         }
        //     }
        // }
    }
}
